"""add pronunciation analysis table

Revision ID: 16be3460fdda
Revises: 5aba4c1b6f95
Create Date: 2026-08-04 13:34:44.385588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16be3460fdda'
down_revision: Union[str, Sequence[str], None] = '5aba4c1b6f95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pronunciation_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('speech_confidence', sa.Float(), nullable=False),
    sa.Column('repeated_word_count', sa.Integer(), nullable=False),
    sa.Column('hesitation_count', sa.Integer(), nullable=False),
    sa.Column('long_pause_count', sa.Integer(), nullable=False),
    sa.Column('overall_pronunciation', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['speech_transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_id')
    )
    op.create_index(op.f('ix_pronunciation_analyses_id'), 'pronunciation_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pronunciation_analyses_id'), table_name='pronunciation_analyses')
    op.drop_table('pronunciation_analyses')
    # ### end Alembic commands ###
