"""add filler word analysis table

Revision ID: 5aba4c1b6f95
Revises: 7b3f5b2a23ad
Create Date: 2026-08-04 13:06:32.760518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5aba4c1b6f95'
down_revision: Union[str, Sequence[str], None] = '7b3f5b2a23ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filler_word_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('detected_words', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['speech_transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_id')
    )
    op.create_index(op.f('ix_filler_word_analyses_id'), 'filler_word_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filler_word_analyses_id'), table_name='filler_word_analyses')
    op.drop_table('filler_word_analyses')
    # ### end Alembic commands ###
