"""add interview report fields

Revision ID: e1638650ce58
Revises: c48a2a6a27e5
Create Date: 2026-07-25 15:59:27.112907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1638650ce58'
down_revision: Union[str, Sequence[str], None] = 'c48a2a6a27e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_reports', sa.Column('missing_topics', sa.Text(), nullable=True))
    op.add_column('interview_reports', sa.Column('learning_resources', sa.Text(), nullable=True))
    op.add_column('interview_reports', sa.Column('suggested_projects', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_reports', 'suggested_projects')
    op.drop_column('interview_reports', 'learning_resources')
    op.drop_column('interview_reports', 'missing_topics')
    # ### end Alembic commands ###
