"""add voice interview tables

Revision ID: eab02296b6e2
Revises: 00068ecd8bf8
Create Date: 2026-08-03 15:51:22.987379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab02296b6e2'
down_revision: Union[str, Sequence[str], None] = '00068ecd8bf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_audios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('audio_format', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['interview_answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id')
    )
    op.create_index(op.f('ix_interview_audios_id'), 'interview_audios', ['id'], unique=False)
    op.create_table('speech_transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_id', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['interview_audios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_id')
    )
    op.create_index(op.f('ix_speech_transcripts_id'), 'speech_transcripts', ['id'], unique=False)
    op.create_table('voice_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio_id', sa.Integer(), nullable=False),
    sa.Column('speech_duration', sa.Float(), nullable=False),
    sa.Column('words_per_minute', sa.Float(), nullable=False),
    sa.Column('pause_count', sa.Integer(), nullable=False),
    sa.Column('average_pause', sa.Float(), nullable=False),
    sa.Column('longest_pause', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['interview_audios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_id')
    )
    op.create_index(op.f('ix_voice_analyses_id'), 'voice_analyses', ['id'], unique=False)
    op.create_table('communication_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript_id', sa.Integer(), nullable=False),
    sa.Column('clarity_score', sa.Float(), nullable=False),
    sa.Column('fluency_score', sa.Float(), nullable=False),
    sa.Column('pace_score', sa.Float(), nullable=False),
    sa.Column('grammar_score', sa.Float(), nullable=False),
    sa.Column('filler_word_score', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['speech_transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transcript_id')
    )
    op.create_index(op.f('ix_communication_scores_id'), 'communication_scores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_communication_scores_id'), table_name='communication_scores')
    op.drop_table('communication_scores')
    op.drop_index(op.f('ix_voice_analyses_id'), table_name='voice_analyses')
    op.drop_table('voice_analyses')
    op.drop_index(op.f('ix_speech_transcripts_id'), table_name='speech_transcripts')
    op.drop_table('speech_transcripts')
    op.drop_index(op.f('ix_interview_audios_id'), table_name='interview_audios')
    op.drop_table('interview_audios')
    # ### end Alembic commands ###
